### ISSUE TITLE
panoramix.vm VM stopped prematurely. Node count 10009 and seconds 1.

### ISSUE THREAD

**Issue by ghost** [palkeo/panoramix#13]
I got this log when decompile contract. How fix it ?

`10:50:03 panoramix.vm VM stopped prematurely. Node count 10009 and seconds 1.`

**Comment by tdudz** [comment]
having the same issue

**Comment by Jesse3692** [comment]
me too

**Comment by palkeo** [comment]
Please send contracts that trigger this error, otherwise I cannot help.
