### ISSUE TITLE
Issue Decompiling Contract 0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8: VM stopped prematurely. Node count 10068 and seconds 1. Problem with unknown128acb08(?)

### ISSUE THREAD

**Issue by JeremyLegere** [palkeo/panoramix#15]
```
VM stopped prematurely. Node count 10068 and seconds 1.
Problem with unknown128acb08(?)
Traceback (most recent call last):
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/decompiler.py", line 177, in _decompile_with_loader
    trace = dec()
  File "/home/jeremy/.local/lib/python3.8/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
    return function(*args, **kwargs)
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/decompiler.py", line 169, in dec
    trace = make_whiles(trace)
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/whiles.py", line 99, in make_whiles
    trace = simplify_trace(trace)
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/simplify.py", line 157, in simplify_trace
    trace = rewrite_trace(trace, split_setmem)
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
    ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
    ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
    ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
  [Previous line repeated 18 more times]
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 203, in rewrite_trace
    res.extend(f(line))
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 268, in split_setmem
    post_split = split_or(mem_val)
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 160, in split_or
    new_memloc = apply_mask_to_range(m.idx, size, offset)
  File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 54, in apply_mask_to_range
    assert safe_le_op(add_op(size_bytes, offset_bytes), range_len) is True, (
AssertionError: (('add', 32, ('mul', -1, ('add', 32, ('mul', -1, ('mem', ('range', ('var', '_830'), 32)))))), 0, 32)
VM stopped prematurely. Node count 11535 and seconds 1.
```

**Comment by JeremyLegere** [comment]
Anyone know how to proceed?

**Comment by bandar909090** [comment]
0x5E646b8216877F9f1b04AAa28720Bb58AdA21b73

**Comment by bandar909090** [comment]
0x5E646b8216877F9f1b04AAa28720Bb58AdA21b73

**Comment by bandar909090** [comment]
> ```
> 
> VM stopped prematurely. Node count 10068 and seconds 1.
> 
> Problem with unknown128acb08(?)
> 
> Traceback (most recent call last):
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/decompiler.py", line 177, in _decompile_with_loader
> 
>     trace = dec()
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
> 
>     return function(*args, **kwargs)
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/decompiler.py", line 169, in dec
> 
>     trace = make_whiles(trace)
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/whiles.py", line 99, in make_whiles
> 
>     trace = simplify_trace(trace)
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/simplify.py", line 157, in simplify_trace
> 
>     trace = rewrite_trace(trace, split_setmem)
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
> 
>     ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
> 
>     ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
> 
>     ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
> 
>   [Previous line repeated 18 more times]
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 203, in rewrite_trace
> 
>     res.extend(f(line))
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 268, in split_setmem
> 
>     post_split = split_or(mem_val)
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 160, in split_or
> 
>     new_memloc = apply_mask_to_range(m.idx, size, offset)
> 
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 54, in apply_mask_to_range
> 
>     assert safe_le_op(add_op(size_bytes, offset_bytes), range_len) is True, (
> 
> AssertionError: (('add', 32, ('mul', -1, ('add', 32, ('mul', -1, ('mem', ('range', ('var', '_830'), 32)))))), 0, 32)
> 
> VM stopped prematurely. Node count 11535 and seconds 1.
> 
> ```

**Comment by palkeo** [comment]
The code is too complex, so it cannot decompile successfully :/

**Comment by bandar909090** [comment]
> ```
> VM stopped prematurely. Node count 10068 and seconds 1.
> Problem with unknown128acb08(?)
> Traceback (most recent call last):
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/decompiler.py", line 177, in _decompile_with_loader
>     trace = dec()
>   File "/home/jeremy/.local/lib/python3.8/site-packages/timeout_decorator/timeout_decorator.py", line 82, in new_function
>     return function(*args, **kwargs)
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/decompiler.py", line 169, in dec
>     trace = make_whiles(trace)
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/whiles.py", line 99, in make_whiles
>     trace = simplify_trace(trace)
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/simplify.py", line 157, in simplify_trace
>     trace = rewrite_trace(trace, split_setmem)
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
>     ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
>     ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 207, in rewrite_trace
>     ("if", cond, rewrite_trace(if_true, f), rewrite_trace(if_false, f))
>   [Previous line repeated 18 more times]
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/utils/helpers.py", line 203, in rewrite_trace
>     res.extend(f(line))
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 268, in split_setmem
>     post_split = split_or(mem_val)
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 160, in split_or
>     new_memloc = apply_mask_to_range(m.idx, size, offset)
>   File "/home/jeremy/.local/lib/python3.8/site-packages/panoramix/core/memloc.py", line 54, in apply_mask_to_range
>     assert safe_le_op(add_op(size_bytes, offset_bytes), range_len) is True, (
> AssertionError: (('add', 32, ('mul', -1, ('add', 32, ('mul', -1, ('mem', ('range', ('var', '_830'), 32)))))), 0, 32)
> VM stopped prematurely. Node count 11535 and seconds 1.
> ```



> الرمز معقد للغاية، لذلك لا يمكن فكه بنجاح :/
