### ISSUE TITLE
https://bscscan.com/tx/0x6d0177284d364c1e3f57dee30b298f421572533fb39896e31d40b8f98f1e23f4

### ISSUE THREAD

**Issue by 4911775157** [palkeo/panoramix#18]
I sent some bitcoins to this wrong address.  How can I recover it?

**Comment by Ramos199200** [comment]
0xdac17f958d2ee523a2206206994597c13d831ec7

**Comment by Carsonmarvel1** [comment]
This address has scam me several times

**Comment by Carsonmarvel1** [comment]
Ramos

0xdac17f958d2ee523a2206206994597c13d831ec7

You stole my coin

**Comment by wallydewey26-design** [comment]
> I sent some bitcoins to this wrong address.  How can I recover it?

**Comment by wallydewey26-design** [comment]
> 0xdac17f958d2ee523a2206206994597c13d831ec7
