### ISSUE TITLE
Unable to decompile

### ISSUE THREAD

**Issue by Marijus** [palkeo/panoramix#21]
Here's the bytecode:

`0xfe6080604052604051610aa6380380610aa683398101604081905261002291610729565b61002c8134610038565b5050505050505061097f565b60008060008060008060007310ed43c718714eb63d5aa57b78b54704e256024e905060006040518060c001604052806000815260200160008152602001600081526020016000815260200160008152602001600081525090506100a2828b8b61012860201b60201c565b6080840152602083018190529082526100bc908b906103c7565b6100d1828b83602001516104f460201b60201c565b60a08401819052606084018290526040840183905283516000819055602085015160018190556002859055600384905560809095015160048190556005839055909e949d50929b5090995090975095509350505050565b604080516002808252606082018352600092839283928392602083019080368337019050509050866001600160a01b031663ad5c46486040518163ffffffff1660e01b815260040160206040518083038186803b15801561018857600080fd5b505afa15801561019c573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101c09190610729565b816000815181106101d3576101d3610953565b60200260200101906001600160a01b031690816001600160a01b031681525050858160018151811061020757610207610953565b6001600160a01b03928316602091820292909201015260405163d06ca61f60e01b815260009189169063d06ca61f9061024690899086906004016108d1565b60006040518083038186803b15801561025e57600080fd5b505afa158015610272573d6000803e3d6000fd5b505050506040513d6000823e601f3d908101601f1916820160405261029a9190810190610759565b90506000816001815181106102b1576102b1610953565b6020026020010151905060005a9050896001600160a01b031663b6f9de958960008730426040518663ffffffff1660e01b81526004016102f4949392919061089c565b6000604051808303818588803b15801561030d57600080fd5b505af1158015610321573d6000803e3d6000fd5b505050505060005a610333908361092e565b6040516370a0823160e01b81523060048201529091508a906000906001600160a01b038316906370a082319060240160206040518083038186803b15801561037a57600080fd5b505afa15801561038e573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906103b2919061083f565b949d949c50919a509298505050505050505050565b60405163095ea7b360e01b81527310ed43c718714eb63d5aa57b78b54704e256024e6004820152600019602482015282906001600160a01b0382169063095ea7b390604401602060405180830381600087803b15801561042657600080fd5b505af1925050508015610456575060408051601f3d908101601f191682019092526104539181019061081d565b60015b6104ee5760405163095ea7b360e01b81527310ed43c718714eb63d5aa57b78b54704e256024e6004820152602481018390526001600160a01b0382169063095ea7b390604401602060405180830381600087803b1580156104b657600080fd5b505af11580156104ca573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906104ee919061081d565b50505050565b604080516002808252606082018352600092839283928392602083019080368337019050509050858160008151811061052f5761052f610953565b60200260200101906001600160a01b031690816001600160a01b031681525050866001600160a01b031663ad5c46486040518163ffffffff1660e01b815260040160206040518083038186803b15801561058857600080fd5b505afa15801561059c573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906105c09190610729565b816001815181106105d3576105d3610953565b6001600160a01b03928316602091820292909201015260405163d06ca61f60e01b815260009189169063d06ca61f9061061290899086906004016108d1565b60006040518083038186803b15801561062a57600080fd5b505afa15801561063e573d6000803e3d6000fd5b505050506040513d6000823e601f3d908101601f191682016040526106669190810190610759565b905060008160018151811061067d5761067d610953565b60200260200101519050600047905060005a60405163791ac94760e01b81529091506001600160a01b038c169063791ac947906106c7908c906000908a90309042906004016108f2565b600060405180830381600087803b1580156106e157600080fd5b505af11580156106f5573d6000803e3d6000fd5b5050505060005a610706908361092e565b90506000610714844761092e565b949d949c50909a509298505050505050505050565b60006020828403121561073b57600080fd5b81516001600160a01b038116811461075257600080fd5b9392505050565b6000602080838503121561076c57600080fd5b82516001600160401b038082111561078357600080fd5b818501915085601f83011261079757600080fd5b8151818111156107a9576107a9610969565b8060051b604051601f19603f830116810181811085821117156107ce576107ce610969565b604052828152858101935084860182860187018a10156107ed57600080fd5b600095505b838610156108105780518552600195909501949386019386016107f2565b5098975050505050505050565b60006020828403121561082f57600080fd5b8151801515811461075257600080fd5b60006020828403121561085157600080fd5b5051919050565b600081518084526020808501945080840160005b838110156108915781516001600160a01b03168752958201959082019060010161086c565b509495945050505050565b8481526080602082015260006108b56080830186610858565b6001600160a01b03949094166040830152506060015292915050565b8281526040602082015260006108ea6040830184610858565b949350505050565b85815284602082015260a06040820152600061091160a0830186610858565b6001600160a01b0394909416606083015250608001529392505050565b60008282101561094e57634e487b7160e01b600052601160045260246000fd5b500390565b634e487b7160e01b600052603260045260246000fd5b634e487b7160e01b600052604160045260246000fd5b6101188061098e6000396000f3fe608060405260043610602a5760003560e01c8063098d322814603557806392093dd614605c57600080fd5b36603057005b600080fd5b348015604057600080fd5b50604960001981565b6040519081526020015b60405180910390f35b348015606757600080fd5b5060b66040805160c08101825260005480825260015460208301819052600254938301849052600354606084018190526004546080850181905260055460a09095018590529295919493909291565b604080519687526020870195909552938501929092526060840152608083015260a082015260c001605356fea2646970667358221220e61b2cbf46961b8942b7c03d52bec7df942b4fe01eddb0595a91c4a994b64ae864736f6c634300080700`

I run the command:

`panoramix bytecode...`

and I get the following:

```
10:34:54 panoramix.decompiler Running light execution to find functions.
10:34:54 panoramix.utils.signatures Cache for PABI found.
10:34:54 panoramix.decompiler Parsing _fallback()...
10:34:54 panoramix.decompiler Functions decompilation finished, now doing post-processing.
# Palkeoramix decompiler. 

def _fallback() payable: # default function
  revert


10:34:54 panoramix.decompiler Running light execution to find functions.
10:34:54 panoramix.utils.signatures Cache for PABI found.
# No code found for this contract.
```

**Comment by palkeo** [comment]
If you have the source code of the contract or how it was built I'm interested, please reopen!

Otherwise I have plenty of similar examples so it doesn't really help.
