### ISSUE TITLE
0xA69585ad16B1ac08dA6b91d8B3f911b582C5deE3

### ISSUE THREAD

**Issue by jbaryy708** [palkeo/panoramix#25]
- [x] ![qr_code_1655156400650.jpg](https://user-images.githubusercontent.com/104515988/173699494-dd753261-b693-4295-a67a-0f25d36b148e.jpg)

**Comment by Sami-ab** [comment]
https://github.com/palkeo/panoramix/issues/25#issue-1271428252/ABA #: 031100092

**Comment by Carsonmarvel1** [comment]
Can you guys help me out i dont know much on programming

**Comment by jbaryy708** [comment]
HI. This is myself, true

**Comment by palkeo** [comment]
Sorry I'm not fluent in QR codes.
