### ISSUE TITLE
Timeout Error and TypeError

### ISSUE THREAD

**Issue by liuxia-haa** [palkeo/panoramix#39]
# Panoramix Issue

We use python 3.8.13 versions and the environment is Linux Ubuntu20.04

1. Timeout Error

   1.  We found that Panoramix often throws timeout exceptions when the number of contract parameters is high in the decompiled expressions. We found that the complexity of algorithm parsing in this part of the code processing logic grows exponentially with the number of parameters, and when the number of parameters is large, the speed of code processing increases greatly, leading to timeout exceptions.

   ```python
   for a given expression, returns variants of it with each value being 0 or 2^256-1
   
   e.g. for ('ADD', ('mem', 64), ('mem', 256))
        returns
           ('ADD', 0, 0),
           ('ADD', 0, MAX_number),
           ('ADD', MAX_number, 0),
           ('ADD', MAX_number, MAX_number)
   
   ```

   b. 我们在测试这个代码的时候遇到了这类错误

   1.  f0d0c1fab0a0f508730ed3ff0e6750bf7411db09\_DocVerify.sol/DocVerify.bin-runtime

   2.  e4564de79f316b5556eaf1bdae221f3770cc3716\_AppProxyUpgradeable.sol/ACL.bin-runtime

   3.  6446ab35c012b10ad7aafc39148da321d7985a0b\_RFIStake.sol/ReflectiveStake.bin-runtime

2. TypeError: can only concatenate tuple (not ""int"") to tuple

   1. We found that the error was a code conversion error

      ```Python
      02:59:16 panoramix.decompiler Running light execution to find functions.
      02:59:16 panoramix.utils.signatures Cache for PABI found.
      02:59:16 panoramix.decompiler Parsing getBySemanticVersion(uint16[3] _semanticVersion)...
      02:59:17 panoramix.decompiler Parsing EVMSCRIPT_REGISTRY_APP_ID()...
      02:59:17 panoramix.decompiler Parsing newVersion(uint16[3] _newSemanticVersion, address _contractAddress, bytes _contentURI)...
      02:59:17 panoramix.vm VM stopped prematurely. Node count 10047 and seconds 0.
      02:59:19 panoramix.decompiler Parsing getByVersionId(uint256 _versionId)...
      02:59:20 panoramix.decompiler Parsing appId()...
      02:59:20 panoramix.decompiler Parsing getInitializationBlock()...
      02:59:20 panoramix.decompiler Parsing getLatestForContractAddress(address _contractAddress)...
      02:59:21 panoramix.decompiler Parsing EVMSCRIPT_REGISTRY_APP()...
      02:59:21 panoramix.decompiler Parsing canPerform(address _sender, bytes32 _role, uint256[] _params)...
      02:59:21 panoramix.decompiler Parsing isValidBump(uint16[3] _oldVersion, uint16[3] _newVersion)...
      02:59:21 panoramix.decompiler Parsing CREATE_VERSION_ROLE()...
      02:59:21 panoramix.decompiler Parsing getLatest()...
      02:59:21 panoramix.decompiler Parsing getVersionsCount()...
      02:59:21 panoramix.decompiler Parsing kernel()...
      02:59:21 panoramix.decompiler Parsing getExecutor(bytes _script)...
      02:59:22 panoramix.decompiler Parsing _fallback()...
      02:59:22 panoramix.decompiler Functions decompilation finished, now doing post-processing.
      02:59:22 panoramix.contract Storage postprocessing failed. This is very bad!
      Traceback (most recent call last):
        File ""/home/liux/.local/lib/python3.8/site-packages/panoramix/contract.py"", line 82, in postprocess
          self.stor_defs = sparser.rewrite_functions(self.functions)
        File ""/home/liux/.local/lib/python3.8/site-packages/panoramix/sparser.py"", line 157, in rewrite_functions
          storages_assoc = _sparser(storages)
        File ""/home/liux/.local/lib/python3.8/site-packages/panoramix/sparser.py"", line 538, in _sparser
          offset += 256 * m.num
      TypeError: can only concatenate tuple (not ""int"") to tuple
      "
      
      ```

**Comment by palkeo** [comment]
Do you have contract addresses, or bytecode, so that I can reproduce?

**Comment by liuxia-haa** [comment]
Thanks for your reply! These are the contract addresses leading to the decompiler throw exceptions.
- **Timeout Error**：
    - **Contract Address:** f0d0c1fab0a0f508730ed3ff0e6750bf7411db09  **File Name:** DocVerify.sol
- **The Error**: `TypeError: can only concatenate tuple (not ""int"") to tuple` occurs in these solidity file:
    - **Contract Address:** 67e72299beaf3f59f365bb4a43e8d02bff61e176  **File Name:** CryptoSagaArenaRecord.sol
    - **Contract Address:** a17e3788787eac51c23e0d04d14f4743737edef  **File Name:** TournamentCore.sol
    - **Contract Address:** 8f64c5e21c4c5b5aedb102e7cacd07ef101bdc7d  **File Name:** APMRegistryFactory.sol
    - **Contract Address:** e4564de79f316b5556eaf1bdae221f3770cc3716  **File Name:** AppProxyUpgradeable.sol
