### ISSUE TITLE
Failures running the tool in Windows

### ISSUE THREAD

**Issue by LimLims** [palkeo/panoramix#6]
I'm having problems running this in Windows. I get a failure to decompile any of the bytecode, as compared with running it on Linux using the same input, which has no problem.

`panoramix.exe 608060405260006002556012600560006101000a81548160ff021916908360ff1602179055506032600e556005600f556032601460006101000a81548163ffffffff021916908363ffffffff1602179055506001601460046101000a81548160ff0219169083151502179055503480156200007957600080fd5b50622625a033600560016101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506000600560009054906101000a900460ff1660ff16600a0a8202905062000133816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054620002c060201b62001e371790919060201c565b6000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055506200019181600254620002c060201b62001e371790919060201c565b600281905550620001a8336200034960201b60201c565b3373ffffffffffffffffffffffffffffffffffffffff16600073ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef836040518082815260200191505060405180910390a3505043601581905550426016819055506040518060400160405280600e81526020017f426f676765642046696e616e6365000000000000000000000000000000000000815250600390805190602001906200026b929190620004ec565b506040518060400160405280600381526020017f424f47000000000000000000000000000000000000000000000000000000000081525060049080519060200190620002b9929190620004ec565b50620005a2565b6000808284019050838110156200033f576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252601b8152602001807f536166654d6174683a206164646974696f6e206f766572666c6f77000000000081525060200191505060405180910390fd5b8091505092915050565b6200035a816200037460201b60201c565b62000371576200037081620003cd60201b60201c565b5b50565b6000600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160009054906101000a900460ff169050919050565b6001600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160006101000a81548160ff021916908315150217905550600780549050600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101819055506007819080600181540180825580915050600190039060005260206000200160009091909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555060086000815480929190600101919050555050565b828054600181600116156101000203166002900490600052602060002090601f01602090048101928262000524576000855562000570565b82601f106200053f57805160ff191683800117855562000570565b8280016001018555821562000570579182015b828111156200056f57825182559160200191906001019062000552565b5b5090506200057f919062000583565b5090565b5b808211156200059e57600081600090555060010162000584565b5090565b6137d480620005b26000396000f3fe608060405234801561001057600080fd5b50600436106102955760003560e01c80635fe8e7cc11610167578063986f3a75116100ce578063b2d4a6f111610087578063b2d4a6f114610d41578063b331108614610d8f578063cbb47d4614610dad578063d4d7b19a14610e05578063dd62ed3e14610e5f578063f2fde38b14610ed757610295565b8063986f3a7514610bf95780639b652d0214610c2d5780639f5a9b7c14610c4d578063a22d483214610c6b578063a694fc3a14610caf578063a9059cbb14610cdd57610295565b80637d8cf4b6116101205780637d8cf4b614610a77578063893d20e814610a815780638d5f81e214610ab557806391c05b0b14610ae957806393005dc214610b1757806395d89b4114610b7657610295565b80635fe8e7cc14610922578063626e1ae71461098157806370a082311461099f578063715018a6146109f757806373889f4a14610a015780637a76646014610a1f57610295565b806326c932601161020b57806342966c68116101c457806342966c68146107fe578063482cd6c51461082c5780634af5da321461084a5780634e0a2d631461086857806351d19a4e146108ac57806351f4ae63146108ca57610295565b806326c93260146106695780632e17de78146106b75780632f54bf6e146106e5578063313ce5671461073f5780633bbac579146107605780633f5ea35c146107ba57610295565b8063176345141161025d578063176345141461042557806318160ddd14610443578063189d165e146104615780631e89d5451461048f578063224b2a5b146105db57806323b872dd146105e557610295565b806306fdde031461029a5780630917e7761461031d578063095ea7b31461033b5780630e53c3341461039f578063131b9c04146103cd575b600080fd5b6102a2610f1b565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156102e25780820151818401526020810190506102c7565b50505050905090810190601f16801561030f5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b610325610fbd565b6040518082815260200191505060405180910390f35b6103876004803603604081101561035157600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050610fc7565b60405180821515815260200191505060405180910390f35b6103cb600480360360208110156103b557600080fd5b8101908080359060200190929190505050610fdb565b005b61040f600480360360208110156103e357600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611005565b6040518082815260200191505060405180910390f35b61042d61106b565b6040518082815260200191505060405180910390f35b61044b611071565b6040518082815260200191505060405180910390f35b61048d6004803603602081101561047757600080fd5b810190808035906020019092919050505061107b565b005b6105d9600480360360408110156104a557600080fd5b81019080803590602001906401000000008111156104c257600080fd5b8201836020820111156104d457600080fd5b803590602001918460208302840111640100000000831117156104f657600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192908035906020019064010000000081111561055657600080fd5b82018360208201111561056857600080fd5b8035906020019184602083028401116401000000008311171561058a57600080fd5b919080806020026020016040519081016040528093929190818152602001838360200280828437600081840152601f19601f8201169050808301925050505050505091929192905050506110a4565b005b6105e361114e565b005b610651600480360360608110156105fb57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050611159565b60405180821515815260200191505060405180910390f35b6106b56004803603604081101561067f57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291908035906020019092919050505061116f565b005b6106e3600480360360208110156106cd57600080fd5b8101908080359060200190929190505050611173565b005b610727600480360360208110156106fb57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611199565b60405180821515815260200191505060405180910390f35b6107476111f3565b604051808260ff16815260200191505060405180910390f35b6107a26004803603602081101561077657600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061120a565b60405180821515815260200191505060405180910390f35b6107fc600480360360208110156107d057600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611263565b005b61082a6004803603602081101561081457600080fd5b8101908080359060200190929190505050611493565b005b6108346114eb565b6040518082815260200191505060405180910390f35b6108526114f5565b6040518082815260200191505060405180910390f35b6108aa6004803603602081101561087e57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506114ff565b005b6108b4611642565b6040518082815260200191505060405180910390f35b61090c600480360360208110156108e057600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061164c565b6040518082815260200191505060405180910390f35b61092a61165e565b6040518080602001828103825283818151815260200191508051906020019060200280838360005b8381101561096d578082015181840152602081019050610952565b505050509050019250505060405180910390f35b6109896116ec565b6040518082815260200191505060405180910390f35b6109e1600480360360208110156109b557600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff1690602001909291905050506116f6565b6040518082815260200191505060405180910390f35b6109ff611758565b005b610a09611776565b6040518082815260200191505060405180910390f35b610a6160048036036020811015610a3557600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611780565b6040518082815260200191505060405180910390f35b610a7f6117cc565b005b610a8961188e565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b610abd6118b8565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b610b1560048036036020811015610aff57600080fd5b81019080803590602001909291905050506118e2565b005b610b1f6119d6565b6040518080602001828103825283818151815260200191508051906020019060200280838360005b83811015610b62578082015181840152602081019050610b47565b505050509050019250505060405180910390f35b610b7e611a64565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610bbe578082015181840152602081019050610ba3565b50505050905090810190601f168015610beb5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b610c2b60048036036020811015610c0f57600080fd5b81019080803563ffffffff169060200190929190505050611b06565b005b610c35611bcb565b60405180821515815260200191505060405180910390f35b610c55611bd4565b6040518082815260200191505060405180910390f35b610cad60048036036020811015610c8157600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611bde565b005b610cdb60048036036020811015610cc557600080fd5b8101908080359060200190929190505050611caa565b005b610d2960048036036040811015610cf357600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050611cd0565b60405180821515815260200191505060405180910390f35b610d8d60048036036040811015610d5757600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190505050611ce5565b005b610d97611ce9565b6040518082815260200191505060405180910390f35b610def60048036036020811015610dc357600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611cef565b6040518082815260200191505060405180910390f35b610e4760048036036020811015610e1b57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611d01565b60405180821515815260200191505060405180910390f35b610ec160048036036040811015610e7557600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611d5a565b6040518082815260200191505060405180910390f35b610f1960048036036020811015610eed57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050611de1565b005b606060038054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610fb35780601f10610f8857610100808354040283529160200191610fb3565b820191906000526020600020905b815481529060010190602001808311610f9657829003601f168201915b5050505050905090565b6000600b54905090565b6000610fd38383611ebf565b905092915050565b610fe433611199565b610fed57600080fd5b6001811015610ffb57600080fd5b80600f8190555050565b600061106461101383611f4c565b600a60008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060020154611e3790919063ffffffff16565b9050919050565b60155481565b6000600254905090565b61108433611199565b61108d57600080fd5b6064811061109a57600080fd5b80600e8190555050565b80518251146110fe576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602681526020018061372c6026913960400191505060405180910390fd5b60005b82518110156111495761113b3384838151811061111a57fe5b602002602001015184848151811061112e57fe5b60200260200101516120c3565b508080600101915050611101565b505050565b6111573361260c565b565b60006111668484846120c3565b90509392505050565b5050565b600960149054906101000a900460ff1661118c57600080fd5b61119633826127c0565b50565b6000600560019054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168273ffffffffffffffffffffffffffffffffffffffff16149050919050565b6000600560009054906101000a900460ff16905090565b6000601160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160009054906101000a900460ff169050919050565b61126c33611199565b61127557600080fd5b61127e8161120a565b61128757600080fd5b6000601160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160006101000a81548160ff021916908315150217905550601360008154809291906001900391905055506000601160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010154905060126001601280549050038154811061135157fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff166012828154811061138957fe5b9060005260206000200160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055508060116000601284815481106113e357fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010181905550601280548061145a57fe5b6001900381819060005260206000200160006101000a81549073ffffffffffffffffffffffffffffffffffffffff021916905590555050565b806000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410156114de57600080fd5b6114e833826129ff565b50565b6000600e54905090565b6000600f54905090565b61150833611199565b61151157600080fd5b61151a81612b30565b61152357600080fd5b6001601160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160006101000a81548160ff021916908315150217905550601280549050601160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101819055506012819080600181540180825580915050600190039060005260206000200160009091909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555060136000815480929190600101919050555050565b6000601354905090565b6000611657826116f6565b9050919050565b606060078054806020026020016040519081016040528092919081815260200182805480156116e257602002820191906000526020600020905b8160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019060010190808311611698575b5050505050905090565b6000600c54905090565b600061175161170483611f4c565b6000808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054611e3790919063ffffffff16565b9050919050565b61176133611199565b61176a57600080fd5b6117746000611de1565b565b6000600854905090565b6000600a60008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600001549050919050565b6117d533611199565b6117de57600080fd5b60005b60078054905081101561188b5760006118306007838154811061180057fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16611780565b9050600081111561187d5761187c6007838154811061184b57fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16826127c0565b5b5080806001019150506117e1565b50565b6000600560019054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b6000600960009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905090565b6118eb3361260c565b806000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054101561193657600080fd5b611987816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054612b7b90919063ffffffff16565b6000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055506119d33382612bc5565b50565b60606012805480602002602001604051908101604052809291908181526020018280548015611a5a57602002820191906000526020600020905b8160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019060010190808311611a10575b5050505050905090565b606060048054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015611afc5780601f10611ad157610100808354040283529160200191611afc565b820191906000526020600020905b815481529060010190602001808311611adf57829003601f168201915b5050505050905090565b611b0f33611199565b611b1857600080fd5b600a8163ffffffff16118015611b3557506103e88163ffffffff16105b611ba7576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260138152602001807f496e76616c6964206d61782074782073697a650000000000000000000000000081525060200191505060405180910390fd5b80601460006101000a81548163ffffffff021916908363ffffffff16021790555050565b60006001905090565b6000601054905090565b611be733611199565b611bf057600080fd5b6000600b5414611c4b576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602c815260200180613773602c913960400191505060405180910390fd5b80600960006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506001600960146101000a81548160ff02191690831515021790555050565b600960149054906101000a900460ff16611cc357600080fd5b611ccd3382612c39565b50565b6000611cdd3384846120c3565b905092915050565b5050565b60165481565b6000611cfa82611f4c565b9050919050565b6000600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160009054906101000a900460ff169050919050565b6000600160008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905092915050565b611dea33611199565b611df357600080fd5b80600560016101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b600080828401905083811015611eb5576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252601b8152602001807f536166654d6174683a206164646974696f6e206f766572666c6f77000000000081525060200191505060405180910390fd5b8091505092915050565b600081600160003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055506001905092915050565b6000600c54600a60008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101541480611fe257506000600a60008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000154145b15611ff057600090506120be565b6000612049600a60008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010154600c54612b7b90919063ffffffff16565b905060006120b6600b546120a8600a60008873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000015485612e4790919063ffffffff16565b612ecd90919063ffffffff16565b905080925050505b919050565b60008073ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff161415612167576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260188152602001807f43616e2774207472616e736665722066726f6d207a65726f000000000000000081525060200191505060405180910390fd5b600073ffffffffffffffffffffffffffffffffffffffff168373ffffffffffffffffffffffffffffffffffffffff16141561220a576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260168152602001807f43616e2774207472616e7366657220746f207a65726f0000000000000000000081525060200191505060405180910390fd5b61221382612f17565b61221c8461260c565b816000808673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205410156122d0576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260128152602001807f4e6f7420656e6f7567682062616c616e6365000000000000000000000000000081525060200191505060405180910390fd5b3373ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff161461244a576123c9826040518060400160405280601481526020017f4e6f7420656e6f75676820616c6c6f77616e6365000000000000000000000000815250600160008873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020546130169092919063ffffffff16565b600160008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055505b600061245685846130d6565b90506124a9816000808873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054612b7b90919063ffffffff16565b6000808773ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555061253c816000808773ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054611e3790919063ffffffff16565b6000808673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555061258785613173565b6125908461318d565b61259b8585856131a7565b8373ffffffffffffffffffffffffffffffffffffffff168573ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef836040518082815260200191505060405180910390a360019150509392505050565b600061261782611780565b1461277457600061262782611f4c565b905061267a816000808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054611e3790919063ffffffff16565b6000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555061271181600a60008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060020154611e3790919063ffffffff16565b600a60008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206002018190555061276c81600d54611e3790919063ffffffff16565b600d81905550505b600c54600a60008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206001018190555050565b80600a60008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000154101561280f57600080fd5b6128188261260c565b61286d81600a60008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000154612b7b90919063ffffffff16565b600a60008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600001819055506128c881600b54612b7b90919063ffffffff16565b600b81905550600960009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663a9059cbb83836040518363ffffffff1660e01b8152600401808373ffffffffffffffffffffffffffffffffffffffff16815260200182815260200192505050602060405180830381600087803b15801561296157600080fd5b505af1158015612975573d6000803e3d6000fd5b505050506040513d602081101561298b57600080fd5b8101908080519060200190929190505050506129a6826132df565b7f0f5bb82176feb1b5e747e28471aa92156a04d9f3ab9f45f28e2d704232b93f758282604051808373ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019250505060405180910390a15050565b6000811415612a0d57612b2c565b612a2281600254612b7b90919063ffffffff16565b600281905550612a3d81601054611e3790919063ffffffff16565b601081905550612a94816000808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054612b7b90919063ffffffff16565b6000808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055507fcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca58282604051808373ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019250505060405180910390a15b5050565b6000807fc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a47060001b90506000833f90506000801b8114158015612b725750818114155b92505050919050565b6000612bbd83836040518060400160405280601e81526020017f536166654d6174683a207375627472616374696f6e206f766572666c6f770000815250613016565b905092915050565b612bda81600c54611e3790919063ffffffff16565b600c819055507f63be20cc905d5ba0cf65db405c4999f99f2575e521875f13a8009d6eed7a09d98282604051808373ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019250505060405180910390a15050565b600960009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166323b872dd8330846040518463ffffffff1660e01b8152600401808473ffffffffffffffffffffffffffffffffffffffff1681526020018373ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019350505050602060405180830381600087803b158015612cea57600080fd5b505af1158015612cfe573d6000803e3d6000fd5b505050506040513d6020811015612d1457600080fd5b810190808051906020019092919050505050612d2f8261260c565b612d8481600a60008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000154611e3790919063ffffffff16565b600a60008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000181905550612ddf81600b54611e3790919063ffffffff16565b600b81905550612dee826132f9565b7f9e71bc8eea02a63969f509818f2dafb9254532904319f9dbda79b67bd34a5f3d8282604051808373ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019250505060405180910390a15050565b600080831415612e5a5760009050612ec7565b6000828402905082848281612e6b57fe5b0414612ec2576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260218152602001806137526021913960400191505060405180910390fd5b809150505b92915050565b6000612f0f83836040518060400160405280601a81526020017f536166654d6174683a206469766973696f6e206279207a65726f000000000000815250613313565b905092915050565b601460049054906101000a900460ff1615612f5c5760008114612f3b576000612f3e565b60015b601460046101000a81548160ff021916908315150217905550613013565b612f9d6103e8612f8f601460009054906101000a900463ffffffff1663ffffffff16600254612e4790919063ffffffff16565b612ecd90919063ffffffff16565b811115613012576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260158152602001807f54782073697a652065786365656473206c696d6974000000000000000000000081525060200191505060405180910390fd5b5b50565b60008383111582906130c3576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825283818151815260200191508051906020019080838360005b8381101561308857808201518184015260208101905061306d565b50505050905090810190601f1680156130b55780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b5060008385039050809150509392505050565b6000806131026103e86130f4600e5486612e4790919063ffffffff16565b612ecd90919063ffffffff16565b905061313984613134600f546131266001600f540386612e4790919063ffffffff16565b612ecd90919063ffffffff16565b612bc5565b61315784613152600f5484612ecd90919063ffffffff16565b6129ff565b61316a8184612b7b90919063ffffffff16565b91505092915050565b61317c816133d9565b61318a5761318981613400565b5b50565b61319681611d01565b6131a4576131a38161360c565b5b50565b60006131b1611642565b14156131bc576132da565b60005b6012805490508110156132d857601281815481106131d957fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663a50e1b3e338686866040518563ffffffff1660e01b8152600401808573ffffffffffffffffffffffffffffffffffffffff1681526020018473ffffffffffffffffffffffffffffffffffffffff1681526020018373ffffffffffffffffffffffffffffffffffffffff168152602001828152602001945050505050600060405180830381600087803b1580156132b057600080fd5b505af19250505080156132c1575060015b6132ca576132cb565b5b80806001019150506131bf565b505b505050565b6132e8816133d9565b6132f6576132f581613400565b5b50565b61330281611d01565b6133105761330f8161360c565b5b50565b600080831182906133bf576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825283818151815260200191508051906020019080838360005b83811015613384578082015181840152602081019050613369565b50505050905090810190601f1680156133b15780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b5060008385816133cb57fe5b049050809150509392505050565b6000806133e5836116f6565b11806133f9575060006133f783611780565b115b9050919050565b6000600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160006101000a81548160ff0219169083151502179055506000600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206001015490506007600160078054905003815481106134b757fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16600782815481106134ef57fe5b9060005260206000200160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550600780548061354257fe5b6001900381819060005260206000200160006101000a81549073ffffffffffffffffffffffffffffffffffffffff0219169055905580600660006007848154811061358957fe5b9060005260206000200160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010181905550600860008154809291906001900391905055505050565b6001600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000160006101000a81548160ff021916908315150217905550600780549050600660008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101819055506007819080600181540180825580915050600190039060005260206000200160009091909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506008600081548092919060010191905055505056fe4163636f756e7473202620616d6f756e7473206d7573742062652073616d65206c656e677468536166654d6174683a206d756c7469706c69636174696f6e206f766572666c6f7743616e6e6f74206368616e67652070616972207768696c7374207468657265206973204c50207374616b6564a264697066735822122021090a7080e27c6e0415bd6ff4122ed57b15d2e306e411ebe1cf44898cb0385a64736f6c63430007060033`

RESULT:

`21:39:52 panoramix.decompiler Running light execution to find functions.
21:39:52 panoramix.utils.signatures Cache for PABI found.
21:39:52 panoramix.decompiler Parsing _fallback()...
21:39:52 panoramix.decompiler Problem with _fallback()
Traceback (most recent call last):
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\panoramix\decompiler.py", line 177, in _decompile_with_loader
    trace = dec()
  File "c:\users\sam\appdata\local\programs\python\python39\lib\site-packages\timeout_decorator\timeout_decorator.py", line 75, in new_function
    old = signal.signal(signal.SIGALRM, handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'
21:39:52 panoramix.decompiler Functions decompilation finished, now doing post-processing.
# Palkeoramix decompiler.
#
#  I failed with these:
#  - _fallback()
#  All the rest is below.
#

`

**Comment by palkeo** [comment]
Hey, I don't have a Windows at hand so not supporting this for now.
