### ISSUE TITLE
Crash complet.

### ISSUE THREAD

**Issue by ytrezq** [palkeo/panoramix#9]
Ça s’arrête sans rien écrire du tout à l’écran au sujet de https://oko.palkeo.com/0x4D1886daf2617cBD9e27abFd0f18a54F04f33c41/code/

et dans le terminal aussi.

**Comment by palkeo** [comment]
Will be fixed in the last version.

**Comment by ytrezq** [comment]
@palkeo : attend, non ! Bien sûr que j’ai aussi essayé ça avec le dernier commit et que ça fait la même chose.
